# Generated by Django 5.2.10 on 2026-01-13 15:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=200)),
                ('donor_type', models.CharField(choices=[('household', 'Household'), ('restaurant', 'Restaurant')], max_length=20)),
                ('donor_phone', models.CharField(max_length=20)),
                ('donor_email', models.EmailField(max_length=254)),
                ('title', models.CharField(help_text="e.g., '5 plates of jollof rice'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.CharField(help_text="e.g., '5 plates' or '2kg'", max_length=100)),
                ('photo_url', models.URLField(blank=True)),
                ('pickup_address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('expiry_time', models.DateTimeField(help_text='When does this food expire?')),
                ('pickup_window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickup_window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('posted', 'Posted'), ('claimed', 'Claimed'), ('picked_up', 'Picked Up'), ('expired', 'Expired')], default='posted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_pin', models.CharField(blank=True, max_length=4)),
                ('pin_created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteer_name', models.CharField(max_length=200)),
                ('volunteer_phone', models.CharField(max_length=20)),
                ('volunteer_email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending (5-min hold)'), ('confirmed', 'Confirmed'), ('picked_up', 'Picked Up'), ('cancelled', 'Cancelled'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('phone_revealed', models.BooleanField(default=False)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='donations.donation')),
            ],
            options={
                'ordering': ['claimed_at'],
            },
        ),
    ]
